### ISSUE TITLE
Use New Media API

### ISSUE THREAD

**Issue by tsadler1988** [bbc/talexample#17]
The example app uses `this._player = new Media('testPlayer', 'video');` which is now deprecated. It should use `this._player = this._device.getMediaPlayer()`.

**Comment by tsadler1988** [comment]
Note that the existing video asset will fail to seek on HTML5 devices using the new media API, as it respects the seekable range reported by the underlying HTML5 video element, which for this asset is 0 - 0. @owensgit found this problem when we tried to upgrade TAL example with the new media API.

**Comment by bxrmbl** [comment]
@tsadler1988 Do you happen to know how to add items to the grid widget? Sorry to randoly ask you. I'm having difficulty with the lack of examples in the documentation. Thank you in advance. Cheers,

**Comment by rosswilson** [comment]
This has now been done 🚢
