### ISSUE TITLE
How to Build/Deploy

### ISSUE THREAD

**Issue by MaPet021** [bbc/talexample#33]
As I didn't found in the documentation I will ask here. 
How can this example be build (prepared for deployment) for use on the TV or some other device?

**Comment by danbrownbox** [comment]
Hi,

I'm almost certain this isn't the best way to do it, but I don't really know node very well, so I'm just going to explain how I got it deployed on Amazon Fire TV.

If you've got it up and running in Node, then you're a good percentage of the way there.

Steps:

1. Follow Node Process with npm install; npm start
2. Navigate to the following URL in your browser: localhost:1337/?brand=amazon&model=firetv
3. View the page source, and save it as index.html
4. Navigate to the node_modules directory in your project dir
5. Copy the tal folder and paste it in the root dir of your project (moving it back one level)
6. You can now delete the node_modules directory as this isn't needed for web based deployment
7. Edit the index.html file you created, and update any references to node_modules/tal to only reference tal (basically delete node_modules from line 13 and 20)
8. Upload the entire project to a webserver
9. On your Amazon Fire TV, install the Web App Tester (search in app store, or get here: https://www.amazon.co.uk/Amazon-Digital-Services-Inc-Tester/dp/B00DZ3I1W8).
10. Add the URL to the web app tester, and click test
11. Example application should load. Remember if you update the files in your server to clear the cache on the web app tester.

I know this isn't very elegant, but it works for me. I think you could omit alot of the steps by building your own index.html using config files from TAL project.

**Comment by kukulaka** [comment]
Hi all, I am sorry no one got back to you with an answer to this issue. Further docs are avaiable at https://github.com/bbc/tal

TAL is deprecated as of 12/12/2022. However, we hope to keep the TAL community up to date with new project plans and will provide an email address that you can use to contact us.
