### ISSUE TITLE
require.ready is not a function

### ISSUE THREAD

**Issue by Undocontrol** [bbc/talexample#34]
I get the subject message thrown front-end when trying to run the helloworld branch - can't seem to understand why, tried on 2 machines

**Comment by kukulaka** [comment]
Hi @Undocontrol, I'm sorry no one got back to you on this issue. Have you followed the instructions found in https://github.com/bbc/tal? 

TAL is now deprecated as of 12/12/2022. We hope to keep the TAL community up to date on future project plans.
