### ISSUE TITLE
How to run talexample on tv emulator/simulator?

### ISSUE THREAD

**Issue by ghost** [bbc/talexample#37]
I am able to run this example on my local machine.
Can you please suggest how to run this example on tv emulator/simulator?

**Comment by Juan-Fran** [comment]
Im looking forward this information too, is there any news?

**Comment by diegocrzt** [comment]
You could try [HybridTVViewer](https://addons.mozilla.org/en-US/firefox/addon/hybridtvviewer/) on Firefox with further [doc](https://github.com/karl-rousseau/HybridTvViewer)

**Comment by kukulaka** [comment]
Hi all, I am sorry no one got back to you with an answer to this issue. Further docs are avaiable at https://github.com/bbc/tal

TAL is deprecated as of 12/12/2022. However, we hope to keep the TAL community up to date with new project plans and will provide an email address that you can use to contact us.
