### ISSUE TITLE
How to complie for LG WebOS TV?

### ISSUE THREAD

**Issue by titus-shoats** [bbc/talexample#38]
Is there a way to compile this for LG WebOS TV Simulator? How do we compile for a tv device such as Samsung, tizen, lg, etc..?
Any advice or help with this?

**Comment by kukulaka** [comment]
Hi @titus-shoats, I'm sorry it has taken a little while for someone to get back to you.  Have you had a look at the [TAL documentation ](https://bbc.github.io/tal/getting-started/introducing-tal.html)? This should help you with this question.

We have [deprecated TAL](https://github.com/bbc/tal#deprecation-announcement-12122022) as od 12/12/2022 but we want to engage more with the community going forward.
